
SRC_FILES	=	day9-2.java Pos2d.java
RUNNER		=	aoc.y2025.day09.day9
INPUT_FILE	=	input.txt
EXAMPLE_FILE	=	example.txt

all	:
	@clear; javac -d . $(SRC_FILES) && java $(RUNNER) $(EXAMPLE_FILE)

run	:
	@clear; javac -d . $(SRC_FILES) && java $(RUNNER) $(INPUT_FILE)

c:
	@rm -rf aoc out