
SRC_FILES	=	day10.java Instruction.java
RUNNER		=	aoc.y2025.day10.day10
INPUT_FILE	=	input.txt
EXAMPLE_FILE	=	example.txt

all	:
	@clear; javac -d . $(SRC_FILES) && java $(RUNNER) $(EXAMPLE_FILE)

run	:
	@clear; javac -d . $(SRC_FILES) && java $(RUNNER) $(INPUT_FILE)

c:
	@rm -rf aoc out