
SRC_FILES	=	day8.java Pos3d.java
RUNNER		=	aoc.day08.day8
INPUT_FILE	=	input.txt
EXAMPLE_FILE	=	example.txt

all	:
	@clear; javac -d . $(SRC_FILES) && java $(RUNNER) $(EXAMPLE_FILE)

run	:
	@clear; javac -d . $(SRC_FILES) && java $(RUNNER) $(INPUT_FILE)

c:
	@rm -rf aoc out